package com.example.demo.cadasterWsdl.producer;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.3.3
 * 2023-02-17T14:29:26.833+06:00
 * Generated source version: 3.3.3
 *
 */
@WebService(targetNamespace = "http://producer.x-road.eu", name = "References")
@XmlSeeAlso({com.example.demo.cadasterWsdl.identifiers.ObjectFactory.class, ObjectFactory.class, com.example.demo.cadasterWsdl.xroad.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface References {

    /**
     * 
     * 
     *       
     */
    @WebMethod(operationName = "GetRestsCurrent")
    @WebResult(name = "GetRestsCurrentResponse", targetNamespace = "http://producer.x-road.eu", partName = "body")
    public GetRestsCurrentResponse getRestsCurrent(

        @WebParam(partName = "body", name = "GetRestsCurrent", targetNamespace = "http://producer.x-road.eu")
        GetRestsCurrent body
    );

    /**
     * 
     * 
     * 
     *       
     */
    @WebMethod(operationName = "GetPersonRightsHtml")
    @WebResult(name = "GetPersonRightsHtmlResponse", targetNamespace = "http://producer.x-road.eu", partName = "body")
    public GetPersonRightsHtmlResponse getPersonRightsHtml(

        @WebParam(partName = "body", name = "GetPersonRightsHtml", targetNamespace = "http://producer.x-road.eu")
        GetPersonRightsHtml body
    );

    /**
     * 
     * 
     *       
     */
    @WebMethod(operationName = "GetTechparameters")
    @WebResult(name = "GetTechparametersResponse", targetNamespace = "http://producer.x-road.eu", partName = "body")
    public GetTechparametersResponse getTechparameters(

        @WebParam(partName = "body", name = "GetTechparameters", targetNamespace = "http://producer.x-road.eu")
        GetTechparameters body
    );

    /**
     * 
     * 
     *       
     */
    @WebMethod(operationName = "GetHistoryRests")
    @WebResult(name = "GetHistoryRestsResponse", targetNamespace = "http://producer.x-road.eu", partName = "body")
    public GetHistoryRestsResponse getHistoryRests(

        @WebParam(partName = "body", name = "GetHistoryRests", targetNamespace = "http://producer.x-road.eu")
        GetHistoryRests body
    );

    /**
     * 
     * 
     * 
     *       
     */
    @WebMethod(operationName = "TechparamPdf")
    @WebResult(name = "TechparamPdfResponse", targetNamespace = "http://producer.x-road.eu", partName = "body")
    public TechparamPdfResponse techparamPdf(

        @WebParam(partName = "body", name = "TechparamPdf", targetNamespace = "http://producer.x-road.eu")
        TechparamPdf body
    );

    /**
     * 
     * 
     * 
     *       
     */
    @WebMethod(operationName = "GetPersonRights")
    @WebResult(name = "GetPersonRightsResponse", targetNamespace = "http://producer.x-road.eu", partName = "body")
    public GetPersonRightsResponse getPersonRights(

        @WebParam(partName = "body", name = "GetPersonRights", targetNamespace = "http://producer.x-road.eu")
        GetPersonRights body
    );

    /**
     * 
     * 
     * 
     *       
     */
    @WebMethod(operationName = "GetPropertyRegInfoByPin")
    @WebResult(name = "GetPropertyRegInfoByPinResponse", targetNamespace = "http://producer.x-road.eu", partName = "body")
    public GetPropertyRegInfoByPinResponse getPropertyRegInfoByPin(

        @WebParam(partName = "body", name = "GetPropertyRegInfoByPin", targetNamespace = "http://producer.x-road.eu")
        GetPropertyRegInfoByPin body
    );

    /**
     * 
     * 
     * 
     *       
     */
    @WebMethod(operationName = "GetProperty")
    @WebResult(name = "GetPropertyResponse", targetNamespace = "http://producer.x-road.eu", partName = "body")
    public GetPropertyResponse getProperty(

        @WebParam(partName = "body", name = "GetProperty", targetNamespace = "http://producer.x-road.eu")
        GetProperty body
    );

    /**
     * 
     * 
     * 
     *       
     */
    @WebMethod(operationName = "GetSoateByPropCode")
    @WebResult(name = "GetSoateByPropCodeResponse", targetNamespace = "http://producer.x-road.eu", partName = "body")
    public GetSoateByPropCodeResponse getSoateByPropCode(

        @WebParam(partName = "body", name = "GetSoateByPropCode", targetNamespace = "http://producer.x-road.eu")
        GetSoateByPropCode body
    );

    /**
     * 
     * 
     * 
     *       
     */
    @WebMethod(operationName = "GetPropertyInfo")
    @WebResult(name = "GetPropertyInfoResponse", targetNamespace = "http://producer.x-road.eu", partName = "body")
    public GetPropertyInfoResponse getPropertyInfo(

        @WebParam(partName = "body", name = "GetPropertyInfo", targetNamespace = "http://producer.x-road.eu")
        GetPropertyInfo body
    );

    /**
     * 
     * 
     * 
     *       
     */
    @WebMethod(operationName = "GetPropertyPdf")
    @WebResult(name = "GetPropertyPdfResponse", targetNamespace = "http://producer.x-road.eu", partName = "body")
    public GetPropertyPdfResponse getPropertyPdf(

        @WebParam(partName = "body", name = "GetPropertyPdf", targetNamespace = "http://producer.x-road.eu")
        GetPropertyPdf body
    );

    /**
     * 
     * 
     * 
     *       
     */
    @WebMethod(operationName = "GetPropertyHistory")
    @WebResult(name = "GetPropertyHistoryResponse", targetNamespace = "http://producer.x-road.eu", partName = "body")
    public GetPropertyHistoryResponse getPropertyHistory(

        @WebParam(partName = "body", name = "GetPropertyHistory", targetNamespace = "http://producer.x-road.eu")
        GetPropertyHistory body
    );

    /**
     * 
     * 
     * 
     *       
     */
    @WebMethod(operationName = "GetPropertyHtml")
    @WebResult(name = "GetPropertyHtmlResponse", targetNamespace = "http://producer.x-road.eu", partName = "body")
    public GetPropertyHtmlResponse getPropertyHtml(

        @WebParam(partName = "body", name = "GetPropertyHtml", targetNamespace = "http://producer.x-road.eu")
        GetPropertyHtml body
    );

    /**
     * 
     * 
     * 
     *       
     */
    @WebMethod(operationName = "TechparamHtml")
    @WebResult(name = "TechparamHtmlResponse", targetNamespace = "http://producer.x-road.eu", partName = "body")
    public TechparamHtmlResponse techparamHtml(

        @WebParam(partName = "body", name = "TechparamHtml", targetNamespace = "http://producer.x-road.eu")
        TechparamHtml body
    );

    /**
     * 
     * 
     * 
     *       
     */
    @WebMethod(operationName = "GetHistoryOwners")
    @WebResult(name = "GetHistoryOwnersResponse", targetNamespace = "http://producer.x-road.eu", partName = "body")
    public GetHistoryOwnersResponse getHistoryOwners(

        @WebParam(partName = "body", name = "GetHistoryOwners", targetNamespace = "http://producer.x-road.eu")
        GetHistoryOwners body
    );

    /**
     * 
     * 
     * 
     *       
     */
    @WebMethod(operationName = "GetPersonRightsPdf")
    @WebResult(name = "GetPersonRightsPdfResponse", targetNamespace = "http://producer.x-road.eu", partName = "body")
    public GetPersonRightsPdfResponse getPersonRightsPdf(

        @WebParam(partName = "body", name = "GetPersonRightsPdf", targetNamespace = "http://producer.x-road.eu")
        GetPersonRightsPdf body
    );

    /**
     * 
     * 
     * 
     *       
     */
    @WebMethod(operationName = "GetOwnersForNalog")
    @WebResult(name = "GetOwnersForNalogResponse", targetNamespace = "http://producer.x-road.eu", partName = "body")
    public GetOwnersForNalogResponse getOwnersForNalog(

        @WebParam(partName = "body", name = "GetOwnersForNalog", targetNamespace = "http://producer.x-road.eu")
        GetOwnersForNalog body
    );

    /**
     * 
     * 
     * 
     *       
     */
    @WebMethod(operationName = "GetPropertyHistoryPdf")
    @WebResult(name = "GetPropertyHistoryPdfResponse", targetNamespace = "http://producer.x-road.eu", partName = "body")
    public GetPropertyHistoryPdfResponse getPropertyHistoryPdf(

        @WebParam(partName = "body", name = "GetPropertyHistoryPdf", targetNamespace = "http://producer.x-road.eu")
        GetPropertyHistoryPdf body
    );

    /**
     * 
     * 
     * 
     *       
     */
    @WebMethod(operationName = "GetOwnersCurrent")
    @WebResult(name = "GetOwnersCurrentResponse", targetNamespace = "http://producer.x-road.eu", partName = "body")
    public GetOwnersCurrentResponse getOwnersCurrent(

        @WebParam(partName = "body", name = "GetOwnersCurrent", targetNamespace = "http://producer.x-road.eu")
        GetOwnersCurrent body
    );

    /**
     * 
     * 
     * 
     *       
     */
    @WebMethod(operationName = "GetPropertyHistoryHtml")
    @WebResult(name = "GetPropertyHistoryHtmlResponse", targetNamespace = "http://producer.x-road.eu", partName = "body")
    public GetPropertyHistoryHtmlResponse getPropertyHistoryHtml(

        @WebParam(partName = "body", name = "GetPropertyHistoryHtml", targetNamespace = "http://producer.x-road.eu")
        GetPropertyHistoryHtml body
    );
}
